//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.Portal.ServiceReferenceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceProxy.IProxyService")]
    public interface IProxyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/Report", ReplyAction="http://tempuri.org/IProxyService/ReportResponse")]
        void Report(int projectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/Report", ReplyAction="http://tempuri.org/IProxyService/ReportResponse")]
        System.Threading.Tasks.Task ReportAsync(int projectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/Notify", ReplyAction="http://tempuri.org/IProxyService/NotifyResponse")]
        void Notify(int taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/Notify", ReplyAction="http://tempuri.org/IProxyService/NotifyResponse")]
        System.Threading.Tasks.Task NotifyAsync(int taskId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProxyServiceChannel : TaskManager.Portal.ServiceReferenceProxy.IProxyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProxyServiceClient : System.ServiceModel.ClientBase<TaskManager.Portal.ServiceReferenceProxy.IProxyService>, TaskManager.Portal.ServiceReferenceProxy.IProxyService {
        
        public ProxyServiceClient() {
        }
        
        public ProxyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProxyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Report(int projectId) {
            base.Channel.Report(projectId);
        }
        
        public System.Threading.Tasks.Task ReportAsync(int projectId) {
            return base.Channel.ReportAsync(projectId);
        }
        
        public void Notify(int taskId) {
            base.Channel.Notify(taskId);
        }
        
        public System.Threading.Tasks.Task NotifyAsync(int taskId) {
            return base.Channel.NotifyAsync(taskId);
        }
    }
}
